
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  <<: *default
  database: coding_challenge_autoscout24_developement

test:
  <<: *default
  database: coding_challenge_autoscout24_test

production:
  <<: *default
  database: coding_challenge_autoscout24_production
  user_name: coding_challenge_autoscout24
